# Generated by Django 4.2.1 on 2023-05-12 14:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InviteCode",
            fields=[
                ("email", models.EmailField(max_length=255, unique=True)),
                (
                    "code",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="RegistrationToken",
        ),
    ]
