# Generated by Django 4.2.1 on 2023-05-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_email_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hobby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Список увлечений",
                "verbose_name_plural": "Списки увлечений",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="hobbies",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="users",
                to="users.hobby",
                verbose_name="Хобби",
            ),
        ),
    ]
