# Generated by Django 4.2.1 on 2023-05-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_hobby_user_hobbies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="hobbies",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="users.hobby", verbose_name="Хобби"
            ),
        ),
    ]
