# Generated by Django 4.2.1 on 2023-05-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_hobbies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users/avatars/",
                verbose_name="Аватар/Фото",
            ),
        ),
    ]
